name: on-call-weekly-datadog-dashboard
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        #cache: 'npm'
    - run: npm install
      
    - name: Get incident count value
      id: incident-count
      run: |
        echo "INCIDENT_COUNT_VALUE=$(node issue_triager/incident_issue_metric_data.js $GITHUB_CONTEXT )">> $GITHUB_OUTPUT
      env:
        DEBUG: true
        PROJECT_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    - name: Get incident count value
        run:|
          echo "The string is:${{ steps.incident-count.outputs.INCIDENT_COUNT_VALUE }}"
