name: on-call-weekly-datadog-dashboard
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 
env:
    DEBUG: true
    PROJECT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
jobs:
  Get-Incident-Count:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        #cache: 'npm'
    - run: npm install
      
    - name: Get incident count value
      id: incident-count
      run: |
        echo "INCIDENT_COUNT_VALUE=$(node issue_triager/incident_issue_metric_data.js $GITHUB_CONTEXT )">> $GITHUB_OUTPUT
  
  report-datadog:
    name: 'Report to DataDog'
    runs-on: ubuntu-20.04
    needs: Get-Incident-Count
    steps:
      - run: echo ${{needs.Get-Incident-Count.outputs.INCIDENT_COUNT_VALUE}}
