name: Enforce incident issue time fill

on:
  issues:
    types: [closed] 
    if: >-
      contains(github.event.issue.labels.*.name, 'Incident')
env:
  COMMITTER_EMAIL: priyakewlani18@github.com
  COMMITTER_NAME: priyanka kewlani
  COMMITTER_USERNAME: priyakewlani18

jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        #cache: 'npm'
    - run: npm install
      
    - name: Set color
      id: random-color-generator
      run: echo "SELECTED_COLOR=$(node issue_triager/incident_issue_time_check.js)">> $GITHUB_OUTPUT
      env:
        DEBUG: true
        PROJECT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Open issue 
      if: ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}
      uses: actions-cool/issues-helper@v3
      with:
        actions: 'get-issue'
        token: ${{ secrets.GITHUB_TOKEN }}
    
