name: Enforce till incident issue till fill

on:
  issues:
    types: [closed] 
    if: >-
      contains(github.event.issue.labels.*.name, 'Incident')
env:
  OUTPUT_FILE_NAME: docs/mttr_report.csv
  COMMITTER_EMAIL: ashishonce@github.com
  COMMITTER_NAME: ashish kumar
  COMMITTER_USERNAME: ashishonce

jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2.2.0
      with:
        node-version: 14
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run issue triager
      run: node issue_triager/incident_issue_time_check.js
      env:
        DEBUG: true
        PROJECT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
