name: Enforce incident issue time fill

on:
  issues:
    types: [closed] 
    if: >-
      contains(github.event.issue.labels.*.name, 'Incident')
env:
  COMMITTER_EMAIL: priyakewlani18@github.com
  COMMITTER_NAME: priyanka kewlani
  COMMITTER_USERNAME: priyakewlani18

jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Run issue triager
      run: |
           isTimePresent= $(node issue_triager/incident_issue_time_check.js)
           echo "$isTimePresent"
           echo "::set-output name=content::$isTimePresent"
      id: timeData
      env:
        DEBUG: true
        PROJECT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: print the value
      run: echo " Time data is ${{ steps.timeData.outputs.content }}"
      
    - name: Add comment on issue
      uses: alexrogalskiy/github-action-issue-commenter@master
      if: ${{ steps.timeData.outputs.content }} == true
      with:
          message: 'Commenting on issue to testify its valid resolution'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
