name: Jobs Testing Output Updated V2

on:
  workflow_dispatch:
env:
  INCOMING_WEBHOOK_URL: "${{secrets.INCOMING_WEBHOOK_INCIDENT_CHANNEL}}"
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    steps:
      - uses: actions/checkout@v2
      
      - id: step1
        run: |
          incident=$(gh issue list --label "Incident" --label "Active" --json "url" | jq '.[] | .url'| tr -d '"')
          incident="${incident//'%'/'%25'}"
          incident="${incident//$'\n'/'%0A'}"
          incident="${incident//$'\r'/'%0D'}"
          echo "test=$incident" >> $GITHUB_OUTPUT

      - name: step2
        run: |
            echo "The string is: ${{ steps.step1.outputs.test }}"
