name: Jobs Testing Output Updated V2

on:
  workflow_dispatch:
env:
  INCOMING_WEBHOOK_URL: "${{secrets.INCOMING_WEBHOOK_INCIDENT_CHANNEL}}"
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - uses: actions/checkout@v2
      
      - id: step1
        run: |
          test=$(gh issue list --label "Incident" --label "Active" --json "url" | jq '.[] | .url' | tr -d '"')
          test="${test//'%'/'%25'}"
          test="${test//$'\n'/'%0A'}"
          test="${test//$'\r'/'%0D'}"
          echo "test=$(test)" >> $GITHUB_OUTPUT
          
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: |
          #pk=$(echo ${{needs.job1.outputs.output1 }}| jq '.[] | .url' | tr -d '"') 
          #echo $pk
          echo ${{needs.job1.outputs.output1 }}
