name: Multiline Output testing
on:
  workflow_dispatch:
env:
  INCOMING_WEBHOOK_URL: "${{secrets.INCOMING_WEBHOOK_INCIDENT_CHANNEL}}"
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    steps:
      - name: create string
        run: |
          MY_STRING=$(cat << EOF
          first line
          second line
          third line
          EOF
          )
          MY_STRING="${MY_STRING//'%'/'%25'}"
          MY_STRING="${MY_STRING//$'\n'/'%0A'}"
          MY_STRING="${MY_STRING//$'\r'/'%0D'}"
          echo "::set-output name=content::$MY_STRING"
        id: my_string
      - name: display string
        run: |
          echo "The string is: ${{ steps.my_string.outputs.content }}"
