name: Ninesapp Alert Issue Update

on:
  issues:
    types: [opened]
  workflow_dispatch:

env:
  OWNER: priyakewlani18
  REPO: demoGithub
  

jobs:
  build:
    #if: contains(github.event.issue.user.login, 'priyakewlani18')
    runs-on: ubuntu-latest
    steps:
      - name: Update comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: 1571425071
          body: |
            **Edit:** Some additional info
          reactions: eyes

