on:
  issues:
    types:
      - closed
  workflow_dispatch:
env:
  JSON: ${{ toJSON(github.event.issue) }}

name: Create scheduled issue from template

jobs:
  build:
    if: contains(github.event.issue.user.login, 'dwivedine')
    runs-on: ubuntu-latest
    steps:
    # Get the title, labels, assignees, and body of the issue template at the path,
    # .github/ISSUE_TEMPLATE/my_template.md, if available.
    - uses: imjohnbo/extract-issue-template-fields@v1
      id: extract
      with:
        path: .github/ISSUE_TEMPLATE/incident.md
        
    - name: define assignees
      id: issue_assignees
      run: |
         echo "names=$(echo "${JSON}" | jq -r '.assignees[].login')" >> $GITHUB_OUTPUT
         
    - name: print assignees
      run: echo ${{ steps.issue_assignees.outputs.names }}

 
    # Create new issue with assignees, labels, title, and body
    - uses: imjohnbo/issue-bot@v3
      with:
        assignees: "priyakewlani18, priyakewlani"
        labels: "Incident, Documentation"
        title: ${{  github.event.issue.title }} - Incident
        body: ${{ steps.extract.outputs.body }}
