name: Ninesapp Alert Issue Update

on:
  issues:
    types: [opened]
  workflow_dispatch:

env:
  OWNER: priyakewlani18
  REPO: demoGithub
  

jobs:
  build:
    #if: contains(github.event.issue.user.login, 'priyakewlani18')
    runs-on: ubuntu-latest
    steps:
    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: 11
        
    - name: print comment
      run:
         echo "${{ steps.fc.outputs.comment-id }} "

    - name: Update comment
      if: steps.fc.outputs.comment-id != ''
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        body: |
          This comment has been updated!
        reactions: hooray

